NỘI DUNG BÀI HỌC :
+ Numpy Base
+ Project nhỏ python 

In [82]:
# Project 1 : dữ liệu cửa hàng xe 

In [83]:
import pandas as pd 
import numpy as np 
import os 


In [84]:
os.chdir("D:")

In [85]:
df = pd.read_csv(r"D:/file.csv")


In [86]:
df.head(5)


Make           Model   Type Origin DriveTrain      MSRP   Invoice  \
0  Acura             MDX    SUV   Asia        All  $36,945   $33,337    
1  Acura  RSX Type S 2dr  Sedan   Asia      Front  $23,820   $21,761    
2  Acura         TSX 4dr  Sedan   Asia      Front  $26,990   $24,647    
3  Acura          TL 4dr  Sedan   Asia      Front  $33,195   $30,299    
4  Acura      3.5 RL 4dr  Sedan   Asia      Front  $43,755   $39,014    

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0         3.5        6.0       265.0      17.0         23.0  4451.0   
1         2.0        4.0       200.0      24.0         31.0  2778.0   
2         2.4        4.0       200.0      22.0         29.0  3230.0   
3         3.2        6.0       270.0      20.0         28.0  3575.0   
4         3.5        6.0       225.0      18.0         24.0  3880.0   

   Wheelbase  Length  
0      106.0   189.0  
1      101.0   172.0  
2      105.0   183.0  
3      108.0   186.0  
4      115.0   197.0

In [87]:
df.info

<bound method DataFrame.info of       Make                    Model   Type  Origin DriveTrain      MSRP  \
0    Acura                      MDX    SUV    Asia        All  $36,945    
1    Acura           RSX Type S 2dr  Sedan    Asia      Front  $23,820    
2    Acura                  TSX 4dr  Sedan    Asia      Front  $26,990    
3    Acura                   TL 4dr  Sedan    Asia      Front  $33,195    
4    Acura               3.5 RL 4dr  Sedan    Asia      Front  $43,755    
..     ...                      ...    ...     ...        ...       ...   
427  Volvo  C70 LPT convertible 2dr  Sedan  Europe      Front  $40,565    
428  Volvo  C70 HPT convertible 2dr  Sedan  Europe      Front  $42,565    
429  Volvo               S80 T6 4dr  Sedan  Europe      Front  $45,210    
430  Volvo                      V40  Wagon  Europe      Front  $26,135    
431  Volvo                     XC70  Wagon  Europe        All  $35,145    

      Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Hig

In [88]:
df.shape

(432, 15)

In [89]:
df.describe()

EngineSize   Cylinders  Horsepower    MPG_City  MPG_Highway  \
count  428.000000  426.000000  428.000000  428.000000   428.000000   
mean     3.196729    5.807512  215.885514   20.060748    26.843458   
std      1.108595    1.558443   71.836032    5.238218     5.741201   
min      1.300000    3.000000   73.000000   10.000000    12.000000   
25%      2.375000    4.000000  165.000000   17.000000    24.000000   
50%      3.000000    6.000000  210.000000   19.000000    26.000000   
75%      3.900000    6.000000  255.000000   21.250000    29.000000   
max      8.300000   12.000000  500.000000   60.000000    66.000000   

            Weight   Wheelbase      Length  
count   428.000000  428.000000  428.000000  
mean   3577.953271  108.154206  186.362150  
std     758.983215    8.311813   14.357991  
min    1850.000000   89.000000  143.000000  
25%    3104.000000  103.000000  178.000000  
50%    3474.500000  107.000000  187.000000  
75%    3977.750000  112.000000  194.000000  
max    7190.000000  144.000000  238.000000

In [90]:
# df.isnull() tìm các giá trị null 
df.isnull().sum() # tổng các giá trị lỗi 

Make           4
Model          4
Type           4
Origin         4
DriveTrain     4
MSRP           4
Invoice        4
EngineSize     4
Cylinders      6
Horsepower     4
MPG_City       4
MPG_Highway    4
Weight         4
Wheelbase      4
Length         4
dtype: int64

In [91]:
# thay thế các giá trị thiếu 
df['Cylinders'].fillna((df["Cylinders"]).mean(), inplace = True)
#inplace : cap nhat lai cac gia tri df 

C:\Users\narut\AppData\Local\Temp\ipykernel_22692\440855311.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cylinders'].fillna((df["Cylinders"]).mean(), inplace = True)


In [92]:
df

Make                    Model   Type  Origin DriveTrain      MSRP  \
0    Acura                      MDX    SUV    Asia        All  $36,945    
1    Acura           RSX Type S 2dr  Sedan    Asia      Front  $23,820    
2    Acura                  TSX 4dr  Sedan    Asia      Front  $26,990    
3    Acura                   TL 4dr  Sedan    Asia      Front  $33,195    
4    Acura               3.5 RL 4dr  Sedan    Asia      Front  $43,755    
..     ...                      ...    ...     ...        ...       ...   
427  Volvo  C70 LPT convertible 2dr  Sedan  Europe      Front  $40,565    
428  Volvo  C70 HPT convertible 2dr  Sedan  Europe      Front  $42,565    
429  Volvo               S80 T6 4dr  Sedan  Europe      Front  $45,210    
430  Volvo                      V40  Wagon  Europe      Front  $26,135    
431  Volvo                     XC70  Wagon  Europe        All  $35,145    

      Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  \
0    $33,337          3.5        6.0       265.0      17.0         23.0   
1    $21,761          2.0        4.0       200.0      24.0         31.0   
2    $24,647          2.4        4.0       200.0      22.0         29.0   
3    $30,299          3.2        6.0       270.0      20.0         28.0   
4    $39,014          3.5        6.0       225.0      18.0         24.0   
..        ...         ...        ...         ...       ...          ...   
427  $38,203          2.4        5.0       197.0      21.0         28.0   
428  $40,083          2.3        5.0       242.0      20.0         26.0   
429  $42,573          2.9        6.0       268.0      19.0         26.0   
430  $24,641          1.9        4.0       170.0      22.0         29.0   
431  $33,112          2.5        5.0       208.0      20.0         27.0   

     Weight  Wheelbase  Length  
0    4451.0      106.0   189.0  
1    2778.0      101.0   172.0  
2    3230.0      105.0   183.0  
3    3575.0      108.0   186.0  
4    3880.0      115.0   197.0  
..      ...        ...     ...  
427  3450.0      105.0   186.0  
428  3450.0      105.0   186.0  
429  3653.0      110.0   190.0  
430  2822.0      101.0   180.0  
431  3823.0      109.0   186.0  

[432 rows x 15 columns]

In [93]:
df["Make"].value_counts()
# tuần suất xuất hiện của các giá trị 

Make
Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Volvo            12
Jaguar           12
Hyundai          12
Subaru           11
Pontiac          11
Mazda            11
Lexus            11
Kia              11
Buick             9
Mercury           9
Lincoln           9
Saturn            8
Cadillac          8
Suzuki            8
Infiniti          8
GMC               8
Acura             7
Porsche           7
Saab              7
Land Rover        3
Oldsmobile        3
Jeep              3
Scion             2
Isuzu             2
MINI              2
Hummer            1
Name: count, dtype: int64

In [94]:
df[df['Origin'].isin(['Asia','Europe'])].head(5)

Make           Model   Type Origin DriveTrain      MSRP   Invoice  \
0  Acura             MDX    SUV   Asia        All  $36,945   $33,337    
1  Acura  RSX Type S 2dr  Sedan   Asia      Front  $23,820   $21,761    
2  Acura         TSX 4dr  Sedan   Asia      Front  $26,990   $24,647    
3  Acura          TL 4dr  Sedan   Asia      Front  $33,195   $30,299    
4  Acura      3.5 RL 4dr  Sedan   Asia      Front  $43,755   $39,014    

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0         3.5        6.0       265.0      17.0         23.0  4451.0   
1         2.0        4.0       200.0      24.0         31.0  2778.0   
2         2.4        4.0       200.0      22.0         29.0  3230.0   
3         3.2        6.0       270.0      20.0         28.0  3575.0   
4         3.5        6.0       225.0      18.0         24.0  3880.0   

   Wheelbase  Length  
0      106.0   189.0  
1      101.0   172.0  
2      105.0   183.0  
3      108.0   186.0  
4      115.0   197.0

In [95]:
df[df['Weight']>=4000]

Make                           Model    Type  Origin DriveTrain  \
0         Acura                             MDX     SUV    Asia        All   
15         Audi  A4 3.0 Quattro convertible 2dr   Sedan  Europe        All   
17         Audi              A6 4.2 Quattro 4dr   Sedan  Europe        All   
18         Audi                A8 L Quattro 4dr   Sedan  Europe        All   
20         Audi                        RS 6 4dr  Sports  Europe      Front   
..          ...                             ...     ...     ...        ...   
405  Volkswagen                      Touareg V6     SUV  Europe        All   
415  Volkswagen                     Phaeton 4dr   Sedan  Europe      Front   
416  Volkswagen                 Phaeton W12 4dr   Sedan  Europe      Front   
419  Volkswagen                       Passat W8   Wagon  Europe      Front   
420       Volvo                         XC90 T6     SUV  Europe        All   

         MSRP   Invoice  EngineSize  Cylinders  Horsepower  MPG_City  \
0    $36,945   $33,337          3.5        6.0       265.0      17.0   
15   $44,240   $40,075          3.0        6.0       220.0      18.0   
17   $49,690   $44,936          4.2        8.0       300.0      17.0   
18   $69,190   $64,740          4.2        8.0       330.0      17.0   
20   $84,600   $76,417          4.2        8.0       450.0      15.0   
..        ...       ...         ...        ...         ...       ...   
405  $35,515   $32,243          3.2        6.0       220.0      15.0   
415  $65,000   $59,912          4.2        8.0       335.0      16.0   
416  $75,000   $69,130          6.0       12.0       420.0      12.0   
419  $40,235   $36,956          4.0        8.0       270.0      18.0   
420  $41,250   $38,851          2.9        6.0       268.0      15.0   

     MPG_Highway  Weight  Wheelbase  Length  
0           23.0  4451.0      106.0   189.0  
15          25.0  4013.0      105.0   180.0  
17          24.0  4024.0      109.0   193.0  
18          24.0  4399.0      121.0   204.0  
20          22.0  4024.0      109.0   191.0  
..           ...     ...        ...     ...  
405         20.0  5086.0      112.0   187.0  
415         22.0  5194.0      118.0   204.0  
416         19.0  5399.0      118.0   204.0  
419         25.0  4067.0      106.0   184.0  
420         20.0  4638.0      113.0   189.0  

[103 rows x 15 columns]

In [96]:
df.head(2)

Make           Model   Type Origin DriveTrain      MSRP   Invoice  \
0  Acura             MDX    SUV   Asia        All  $36,945   $33,337    
1  Acura  RSX Type S 2dr  Sedan   Asia      Front  $23,820   $21,761    

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0         3.5        6.0       265.0      17.0         23.0  4451.0   
1         2.0        4.0       200.0      24.0         31.0  2778.0   

   Wheelbase  Length  
0      106.0   189.0  
1      101.0   172.0

In [97]:
df['MPG_City'] = df['MPG_City'].apply(lambda x : x+3)

In [98]:
df.head(5)

Make           Model   Type Origin DriveTrain      MSRP   Invoice  \
0  Acura             MDX    SUV   Asia        All  $36,945   $33,337    
1  Acura  RSX Type S 2dr  Sedan   Asia      Front  $23,820   $21,761    
2  Acura         TSX 4dr  Sedan   Asia      Front  $26,990   $24,647    
3  Acura          TL 4dr  Sedan   Asia      Front  $33,195   $30,299    
4  Acura      3.5 RL 4dr  Sedan   Asia      Front  $43,755   $39,014    

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0         3.5        6.0       265.0      20.0         23.0  4451.0   
1         2.0        4.0       200.0      27.0         31.0  2778.0   
2         2.4        4.0       200.0      25.0         29.0  3230.0   
3         3.2        6.0       270.0      23.0         28.0  3575.0   
4         3.5        6.0       225.0      21.0         24.0  3880.0   

   Wheelbase  Length  
0      106.0   189.0  
1      101.0   172.0  
2      105.0   183.0  
3      108.0   186.0  
4      115.0   197.0

In [99]:
# Project 2 : Weather dataset 

In [100]:
df1 = pd.read_csv(r"D:/file1.csv")

In [101]:
df1.head(10)

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00    -1.8              -3.9         86                4   
1  1/1/2012 1:00    -1.8              -3.7         87                4   
2  1/1/2012 2:00    -1.8              -3.4         89                7   
3  1/1/2012 3:00    -1.5              -3.2         88                6   
4  1/1/2012 4:00    -1.5              -3.3         88                7   
5  1/1/2012 5:00    -1.4              -3.3         87                9   
6  1/1/2012 6:00    -1.5              -3.1         89                7   
7  1/1/2012 7:00    -1.4              -3.6         85                7   
8  1/1/2012 8:00    -1.4              -3.6         85                9   
9  1/1/2012 9:00    -1.3              -3.1         88               15   

   Visibility_km  Press_kPa               Weather  
0            8.0     101.24                   Fog  
1            8.0     101.24                   Fog  
2            4.0     101.26  Freezing Drizzle,Fog  
3            4.0     101.27  Freezing Drizzle,Fog  
4            4.8     101.23                   Fog  
5            6.4     101.27                   Fog  
6            6.4     101.29                   Fog  
7            8.0     101.26                   Fog  
8            8.0     101.23                   Fog  
9            4.0     101.20                   Fog

In [102]:
df1.index

RangeIndex(start=0, stop=8784, step=1)

In [103]:
df1.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [104]:
df1.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [105]:
df1['Weather'].unique() # trả về các cột duy nhất 

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [106]:
df1.nunique() 

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [107]:
df1.count() # Đếm dữ liệu 

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [108]:
df1['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                

In [109]:
df1.info

<bound method DataFrame.info of              Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4   
1        1/1/2012 1:00    -1.8              -3.7         87                4   
2        1/1/2012 2:00    -1.8              -3.4         89                7   
3        1/1/2012 3:00    -1.5              -3.2         88                6   
4        1/1/2012 4:00    -1.5              -3.3         88                7   
...                ...     ...               ...        ...              ...   
8779  12/31/2012 19:00     0.1              -2.7         81               30   
8780  12/31/2012 20:00     0.2              -2.4         83               24   
8781  12/31/2012 21:00    -0.5              -1.5         93               28   
8782  12/31/2012 22:00    -0.2              -1.8         89               28   
8783  12/31/2012 23:00     0.0              -2.1         86               30   

      V

In [110]:
df1.head(5)

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00    -1.8              -3.9         86                4   
1  1/1/2012 1:00    -1.8              -3.7         87                4   
2  1/1/2012 2:00    -1.8              -3.4         89                7   
3  1/1/2012 3:00    -1.5              -3.2         88                6   
4  1/1/2012 4:00    -1.5              -3.3         88                7   

   Visibility_km  Press_kPa               Weather  
0            8.0     101.24                   Fog  
1            8.0     101.24                   Fog  
2            4.0     101.26  Freezing Drizzle,Fog  
3            4.0     101.27  Freezing Drizzle,Fog  
4            4.8     101.23                   Fog

In [111]:
df1.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [112]:
df1['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

In [113]:
df1.head(2)

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00    -1.8              -3.9         86                4   
1  1/1/2012 1:00    -1.8              -3.7         87                4   

   Visibility_km  Press_kPa Weather  
0            8.0     101.24     Fog  
1            8.0     101.24     Fog

In [114]:
df1.Weather.value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                

In [115]:
df1[df1.Weather=='Clear']

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
67      1/3/2012 19:00   -16.9             -24.8         50               24   
114     1/5/2012 18:00    -7.1             -14.4         56               11   
115     1/5/2012 19:00    -9.2             -15.4         61                7   
116     1/5/2012 20:00    -9.8             -15.7         62                9   
117     1/5/2012 21:00    -9.0             -14.8         63               13   
...                ...     ...               ...        ...              ...   
8646   12/26/2012 6:00   -13.4             -14.8         89                4   
8698  12/28/2012 10:00    -6.1              -8.6         82               19   
8713   12/29/2012 1:00   -11.9             -13.6         87               11   
8714   12/29/2012 2:00   -11.8             -13.1         90               13   
8756  12/30/2012 20:00   -13.8             -16.5         80               24   

      Visibility_km  Press_kPa Weather  
67             25.0     101.74   Clear  
114            25.0     100.71   Clear  
115            25.0     100.80   Clear  
116            25.0     100.83   Clear  
117            25.0     100.83   Clear  
...             ...        ...     ...  
8646           25.0     102.47   Clear  
8698           24.1     101.27   Clear  
8713           25.0     101.31   Clear  
8714           25.0     101.33   Clear  
8756           25.0     101.52   Clear  

[1326 rows x 8 columns]

In [116]:
df1.groupby('Weather').get_group('Clear')

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
67      1/3/2012 19:00   -16.9             -24.8         50               24   
114     1/5/2012 18:00    -7.1             -14.4         56               11   
115     1/5/2012 19:00    -9.2             -15.4         61                7   
116     1/5/2012 20:00    -9.8             -15.7         62                9   
117     1/5/2012 21:00    -9.0             -14.8         63               13   
...                ...     ...               ...        ...              ...   
8646   12/26/2012 6:00   -13.4             -14.8         89                4   
8698  12/28/2012 10:00    -6.1              -8.6         82               19   
8713   12/29/2012 1:00   -11.9             -13.6         87               11   
8714   12/29/2012 2:00   -11.8             -13.1         90               13   
8756  12/30/2012 20:00   -13.8             -16.5         80               24   

      Visibility_km  Press_kPa Weather  
67             25.0     101.74   Clear  
114            25.0     100.71   Clear  
115            25.0     100.80   Clear  
116            25.0     100.83   Clear  
117            25.0     100.83   Clear  
...             ...        ...     ...  
8646           25.0     102.47   Clear  
8698           24.1     101.27   Clear  
8713           25.0     101.31   Clear  
8714           25.0     101.33   Clear  
8756           25.0     101.52   Clear  

[1326 rows x 8 columns]

In [117]:
df1.head(2)

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00    -1.8              -3.9         86                4   
1  1/1/2012 1:00    -1.8              -3.7         87                4   

   Visibility_km  Press_kPa Weather  
0            8.0     101.24     Fog  
1            8.0     101.24     Fog

In [118]:
df1[df1['Wind Speed_km/h'] == 4]

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4   
1        1/1/2012 1:00    -1.8              -3.7         87                4   
96       1/5/2012 0:00    -8.8             -11.7         79                4   
101      1/5/2012 5:00    -7.0              -9.5         82                4   
146      1/7/2012 2:00    -8.1             -11.1         79                4   
...                ...     ...               ...        ...              ...   
8768   12/31/2012 8:00    -8.6             -10.3         87                4   
8769   12/31/2012 9:00    -8.1              -9.6         89                4   
8770  12/31/2012 10:00    -7.4              -8.9         89                4   
8772  12/31/2012 12:00    -5.8              -7.5         88                4   
8773  12/31/2012 13:00    -4.6              -6.6         86                4   

      Visibility_km  Press_kPa       Weather  
0               8.0     101.24           Fog  
1               8.0     101.24           Fog  
96              9.7     100.32          Snow  
101             4.0     100.19          Snow  
146            19.3     100.15        Cloudy  
...             ...        ...           ...  
8768            3.2     101.14  Snow Showers  
8769            2.4     101.09          Snow  
8770            6.4     101.05      Snow,Fog  
8772           12.9     100.78          Snow  
8773           12.9     100.63          Snow  

[474 rows x 8 columns]

In [119]:
df1.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [120]:
df1.notnull().sum()


Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [121]:
df1.head(2)


Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00    -1.8              -3.9         86                4   
1  1/1/2012 1:00    -1.8              -3.7         87                4   

   Visibility_km  Press_kPa Weather  
0            8.0     101.24     Fog  
1            8.0     101.24     Fog

In [122]:
df1.rename(columns={'Weather':'Weather Condition'})

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4   
1        1/1/2012 1:00    -1.8              -3.7         87                4   
2        1/1/2012 2:00    -1.8              -3.4         89                7   
3        1/1/2012 3:00    -1.5              -3.2         88                6   
4        1/1/2012 4:00    -1.5              -3.3         88                7   
...                ...     ...               ...        ...              ...   
8779  12/31/2012 19:00     0.1              -2.7         81               30   
8780  12/31/2012 20:00     0.2              -2.4         83               24   
8781  12/31/2012 21:00    -0.5              -1.5         93               28   
8782  12/31/2012 22:00    -0.2              -1.8         89               28   
8783  12/31/2012 23:00     0.0              -2.1         86               30   

      Visibility_km  Press_kPa     Weather Condition  
0               8.0     101.24                   Fog  
1               8.0     101.24                   Fog  
2               4.0     101.26  Freezing Drizzle,Fog  
3               4.0     101.27  Freezing Drizzle,Fog  
4               4.8     101.23                   Fog  
...             ...        ...                   ...  
8779            9.7     100.13                  Snow  
8780            9.7     100.03                  Snow  
8781            4.8      99.95                  Snow  
8782            9.7      99.91                  Snow  
8783           11.3      99.89                  Snow  

[8784 rows x 8 columns]

In [123]:
df1.Visibility_km.mean() # gia tri trung binh 

27.664446721311478

In [124]:
df1.Press_kPa.std()

0.8440047459486483

In [125]:
df1['Rel Hum_%'].var()
# độ lệch bình phương trung bình 

286.24855019850196

In [126]:
df1['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                

In [127]:
df1[df1['Weather']=='Snow']

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
55       1/3/2012 7:00   -14.0             -19.5         63               19   
84      1/4/2012 12:00   -13.7             -21.7         51               11   
86      1/4/2012 14:00   -11.3             -19.0         53                7   
87      1/4/2012 15:00   -10.2             -16.3         61               11   
88      1/4/2012 16:00    -9.4             -15.5         61               13   
...                ...     ...               ...        ...              ...   
8779  12/31/2012 19:00     0.1              -2.7         81               30   
8780  12/31/2012 20:00     0.2              -2.4         83               24   
8781  12/31/2012 21:00    -0.5              -1.5         93               28   
8782  12/31/2012 22:00    -0.2              -1.8         89               28   
8783  12/31/2012 23:00     0.0              -2.1         86               30   

      Visibility_km  Press_kPa Weather  
55             25.0     100.95    Snow  
84             24.1     101.25    Snow  
86             19.3     100.97    Snow  
87              9.7     100.89    Snow  
88             19.3     100.79    Snow  
...             ...        ...     ...  
8779            9.7     100.13    Snow  
8780            9.7     100.03    Snow  
8781            4.8      99.95    Snow  
8782            9.7      99.91    Snow  
8783           11.3      99.89    Snow  

[390 rows x 8 columns]

In [128]:
df1[df1['Weather'].str.contains('Snow')].tail(50)
# Lấy 50 hàng cuối 

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
8680  12/27/2012 16:00    -4.5              -6.2         88               37   
8681  12/27/2012 17:00    -4.2              -5.9         88               32   
8682  12/27/2012 18:00    -4.0              -5.7         88               28   
8683  12/27/2012 19:00    -3.9              -5.6         88               26   
8684  12/27/2012 20:00    -3.7              -5.3         89               37   
8685  12/27/2012 21:00    -3.7              -4.8         92               24   
8686  12/27/2012 22:00    -3.8              -4.6         94               20   
8687  12/27/2012 23:00    -4.0              -5.6         89               24   
8688   12/28/2012 0:00    -4.2              -5.7         89               19   
8689   12/28/2012 1:00    -4.4              -6.6         85               15   
8690   12/28/2012 2:00    -4.3              -6.3         86               11   
8691   12/28/2012 3:00    -4.6              -5.9         91               13   
8692   12/28/2012 4:00    -4.9              -5.9         93                9   
8723  12/29/2012 11:00   -10.9             -12.2         90                7   
8724  12/29/2012 12:00   -10.5             -11.6         92               11   
8725  12/29/2012 13:00   -10.0             -11.1         92               22   
8726  12/29/2012 14:00    -9.3             -10.5         91               22   
8727  12/29/2012 15:00    -8.8             -10.0         91               20   
8728  12/29/2012 16:00    -8.5              -9.9         90               24   
8729  12/29/2012 17:00    -9.0             -10.4         90               19   
8730  12/29/2012 18:00    -9.3             -10.9         88               26   
8731  12/29/2012 19:00    -9.5             -11.2         87               26   
8732  12/29/2012 20:00    -9.7             -11.6         86               24   
8733  12/29/2012 21:00    -9.8             -11.8         85               24   
8734  12/29/2012 22:00   -10.1             -11.6         89               15   
8735  12/29/2012 23:00   -10.0             -12.0         85               20   
8736   12/30/2012 0:00    -9.6             -11.3         87               13   
8737   12/30/2012 1:00    -9.4             -10.5         92                9   
8738   12/30/2012 2:00    -9.3             -10.4         92                9   
8739   12/30/2012 3:00    -9.1             -10.4         90               11   
8740   12/30/2012 4:00    -9.3             -10.6         90               13   
8741   12/30/2012 5:00    -9.1             -10.4         90               11   
8742   12/30/2012 6:00    -9.3             -10.8         89               17   
8767   12/31/2012 7:00    -9.3             -11.3         85                0   
8768   12/31/2012 8:00    -8.6             -10.3         87                4   
8769   12/31/2012 9:00    -8.1              -9.6         89                4   
8770  12/31/2012 10:00    -7.4              -8.9         89                4   
8771  12/31/2012 11:00    -6.7              -7.9         91                9   
8772  12/31/2012 12:00    -5.8              -7.5         88                4   
8773  12/31/2012 13:00    -4.6              -6.6         86                4   
8774  12/31/2012 14:00    -3.4              -5.7         84                6   
8775  12/31/2012 15:00    -2.3              -4.6         84                9   
8776  12/31/2012 16:00    -1.4              -4.0         82               13   
8777  12/31/2012 17:00    -1.1              -3.3         85               19   
8778  12/31/2012 18:00    -1.3              -3.1         88               17   
8779  12/31/2012 19:00     0.1              -2.7         81               30   
8780  12/31/2012 20:00     0.2              -2.4         83               24   
8781  12/31/2012 21:00    -0.5              -1.5         93               28   
8782  12/31/2012 22:00    -0.2              -1.8         89               28   
8783  12/31/2

In [129]:
df1.head(2)

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00    -1.8              -3.9         86                4   
1  1/1/2012 1:00    -1.8              -3.7         87                4   

   Visibility_km  Press_kPa Weather  
0            8.0     101.24     Fog  
1            8.0     101.24     Fog

In [130]:
df1[df1['Wind Speed_km/h']>24 & (df1['Visibility_km']==2)]

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4   
1        1/1/2012 1:00    -1.8              -3.7         87                4   
2        1/1/2012 2:00    -1.8              -3.4         89                7   
3        1/1/2012 3:00    -1.5              -3.2         88                6   
4        1/1/2012 4:00    -1.5              -3.3         88                7   
...                ...     ...               ...        ...              ...   
8779  12/31/2012 19:00     0.1              -2.7         81               30   
8780  12/31/2012 20:00     0.2              -2.4         83               24   
8781  12/31/2012 21:00    -0.5              -1.5         93               28   
8782  12/31/2012 22:00    -0.2              -1.8         89               28   
8783  12/31/2012 23:00     0.0              -2.1         86               30   

      Visibility_km  Press_kPa               Weather  
0               8.0     101.24                   Fog  
1               8.0     101.24                   Fog  
2               4.0     101.26  Freezing Drizzle,Fog  
3               4.0     101.27  Freezing Drizzle,Fog  
4               4.8     101.23                   Fog  
...             ...        ...                   ...  
8779            9.7     100.13                  Snow  
8780            9.7     100.03                  Snow  
8781            4.8      99.95                  Snow  
8782            9.7      99.91                  Snow  
8783           11.3      99.89                  Snow  

[8475 rows x 8 columns]

In [131]:
df1.groupby('Weather').min()


Date/Time  Temp_C  \
Weather                                                             
Clear                                      1/11/2012 1:00   -23.3   
Cloudy                                     1/1/2012 17:00   -21.4   
Drizzle                                   1/23/2012 21:00     1.1   
Drizzle,Fog                               1/23/2012 20:00     0.0   
Drizzle,Ice Pellets,Fog                   12/17/2012 9:00     0.4   
Drizzle,Snow                             12/17/2012 15:00     0.9   
Drizzle,Snow,Fog                         12/18/2012 21:00     0.3   
Fog                                         1/1/2012 0:00   -16.0   
Freezing Drizzle                          1/13/2012 10:00    -9.0   
Freezing Drizzle,Fog                        1/1/2012 2:00    -6.4   
Freezing Drizzle,Haze                      2/1/2012 11:00    -5.8   
Freezing Drizzle,Snow                      1/13/2012 3:00    -8.3   
Freezing Fog                               1/22/2012 6:00   -19.0   
Freezing Rain                             1/13/2012 11:00    -6.5   
Freezing Rain,Fog                         1/17/2012 23:00    -6.1   
Freezing Rain,Haze                         2/1/2012 14:00    -4.9   
Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00    -2.6   
Freezing Rain,Snow Grains                  1/13/2012 9:00    -5.0   
Haze                                      1/22/2012 12:00   -11.5   
Mainly Clear                              1/10/2012 11:00   -22.8   
Moderate Rain,Fog                         12/10/2012 8:00     1.7   
Moderate Snow                             1/12/2012 15:00    -6.3   
Moderate Snow,Blowing Snow               12/27/2012 10:00    -5.5   
Mostly Cloudy                              1/1/2012 16:00   -23.2   
Rain                                       1/1/2012 18:00     0.3   
Rain Showers                               1/1/2012 22:00     1.6   
Rain Showers,Fog                          10/20/2012 3:00    12.8   
Rain Showers,Snow Showers                  11/4/2012 8:00     2.1   
Rain,Fog                                  1/23/2012 18:00     0.0   
Rain,Haze                                  3/13/2012 7:00     4.0   
Rain,Ice Pellets                          12/18/2012 5:00     0.6   
Rain,Snow                                  1/10/2012 5:00     0.6   
Rain,Snow Grains                          12/21/2012 0:00     1.9   
Rain,Snow,Fog                             12/8/2012 21:00     0.8   
Rain,Snow,Ice Pellets                     12/21/2012 1:00     0.9   
Snow                                       1/10/2012 1:00   -16.7   
Snow Pellets                             11/24/2012 15:00     0.7   
Snow Showers                               1/12/2012 7:00   -13.3   
Snow Showers,Fog                          12/26/2012 9:00   -11.3   
Snow,Blowing Snow                         1/13/2012 21:00   -12.0   
Snow,Fog                                 12/16/2012 15:00   -10.1   
Snow,Haze                                  2/1/2012 17:00    -4.3   
Snow,Ice Pellets                          12/10/2012 3:00    -4.3   
Thunderstorms                              7/16/2012 1:00    21.6   
Thunderstorms,Heavy Rain Showers           5/29/2012 6:00    10.9   
Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00    19.6   
Thunderstorms,Rain                        5/25/2012 20:00    19.4   
Thunderstorms,Rain Showers                5/29/2012 16:00    11.0   
Thunderstorms,Rain Showers,Fog             6/29/2012 3:00    19.5   
Thunderstorms,Rain,Fog                     7/17/2012 5:00    20.6   

                                         Dew Point Temp_C  Rel Hum_%  \
Weather                                                                
Clear                                               -28.5         20   
Cloudy                                              -26.8         18   
Drizzle                                              -0.2         74   
Drizzle,Fog                                          -1.6         85   
Drizzle,Ice Pellets,Fog    

In [132]:
# Base Numpy 

In [133]:
import numpy as np 

In [134]:
# Create arrays : 
a = [1,2,3] 
a3= np.array(a) 
b = [[1,2,3],[4,5,6],[7,8,9]]
b3=np.array(b) 

# arange : 
b1 = np.arange(0,10) 

b2 = np.arange(0,11,2) 

print('Mang1:',a3,'\nMang2:\n',b3,'\nMang3',b1,'\nMang4',b2)


Mang1: [1 2 3] 
Mang2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
Mang3 [0 1 2 3 4 5 6 7 8 9] 
Mang4 [ 0  2  4  6  8 10]


In [135]:
# Ma trận 0 :
a1= np.zeros(3) 
a2= np.zeros((5,5))
# Ma trận 1 :
a3= np.ones(3)
a4= np.ones((5,5))
# linspace :
a5= np.linspace(0,10,3) 

# Ma trận chéo :
a6= np.eye(4)
# ma trận ngẫu nhiên :
a7= np.random.rand(5,5)  
a8= np.random.randn(5,5) 
# ma trận số tự nhiên :
a9= np.random.randint(1,100,5) 

#in matrix 

print("Mang1:",a1)
print("Mang1.1:\n",a2)
print("Mang2:",a3)
print("Mang2.1:\n",a4)
print("Mang3:",a5)
print("Mang4:\n",a6)
print("Mang5:\n",a7)

Mang1: [0. 0. 0.]
Mang1.1:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Mang2: [1. 1. 1.]
Mang2.1:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Mang3: [ 0.  5. 10.]
Mang4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Mang5:
 [[0.38006789 0.20793915 0.12636243 0.01458378 0.94352493]
 [0.98730121 0.75552166 0.5807774  0.826743   0.877665  ]
 [0.73268534 0.31892165 0.91493837 0.49846373 0.26640258]
 [0.39283804 0.663417   0.07123163 0.98162012 0.81051157]
 [0.45946864 0.37069827 0.85321757 0.84890633 0.80858041]]


In [136]:
print("Mang6:\n",a8)
print("Mang7:\n",a9)

Mang6:
 [[-0.140684    0.04505347 -0.64303219  1.074135    0.72140816]
 [-0.28607304 -1.21784376 -2.85151987 -0.43172475 -0.1321504 ]
 [-1.27072579  1.38494988 -0.66472193  1.34208008  0.53548914]
 [ 1.38655867  0.28857326  1.12301397  1.46950763  0.77219116]
 [ 0.29292546 -1.32951549  1.29198536  0.48874335  0.15036066]]
Mang7:
 [30 24 92 27 27]


In [137]:
a = np.arange(25) 
b = np.random.randint(0,50,10) 
arr = np.arange(25)
# reshape  
a.reshape(5,5) 

# Min , max , argmin , argmax 
b.min() 
b.max()
b.argmin()
b.argmax() 

# shape 
arr.shape 
arr.reshape(1,25).shape

# dtype 
arr.dtype 

dtype('int32')

In [138]:
arr = np.arange(0,11) 

#index :
a1 =arr[8] 
a2 =arr[1:5] 
a3 =arr[0:5] 
print(a1)
print(a2)
print(a3)

8
[1 2 3 4]
[0 1 2 3 4]


In [139]:
# phát hành hàng loạt : 
  # Cách 1 : 
#a1 = arr[0:5]=100 
#print(a1)
	# Cách 2 : 
a2= arr = np.arange(0,11)
print(a2)
slice_of_arr = arr[0:6] 
slice_of_arr[:]=99 
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[99 99 99 99 99 99  6  7  8  9 10]


In [140]:
arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]


In [141]:
# tạo mảng 2D : 
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45])) 
# thao tác : 
b1=arr_2d[1] 
b2=arr_2d[1][0] 
b3=arr_2d[:2,1:] 
b4=arr_2d[2,:]
print("mang1:",b1)
print("mang2:",b2)
print("mang3:\n",b3)
print("mang4:",b4)
 

mang1: [20 25 30]
mang2: 20
mang3:
 [[10 15]
 [25 30]]
mang4: [35 40 45]


In [142]:
# tạo mảng hàng loạt : 
arr2d = np.zeros((10,10)) 
arr_length = arr2d.shape[1] 
for i in range(arr_length):
    arr2d[i] = i  

arr2d 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [143]:
arr = np.arange(1,11) 
bool_arr = arr>4 
a1=arr[bool_arr]
a2=arr[arr>2]
print(a1)
print(a2)
print(bool_arr)


[ 5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True  True  True]


In [144]:
#xu li mang 

In [145]:
arr = np.arange(0,10) 

arr + arr 
arr * arr
arr - arr
arr/arr 
a1=np.sqrt(arr) # căn bậc 2 
a2=np.exp(arr) # (e^) 
a3=np.sin(arr) 
a3=np.log(arr)

C:\Users\narut\AppData\Local\Temp\ipykernel_22692\3293463388.py:6: RuntimeWarning: invalid value encountered in divide
  arr/arr
C:\Users\narut\AppData\Local\Temp\ipykernel_22692\3293463388.py:10: RuntimeWarning: divide by zero encountered in log
  a3=np.log(arr)


In [146]:
x = np.array([0, 1, 2, 3])
a1=np.add.reduce(x) # giá trị tổng hợp . 
print(a1)
a2=np.multiply.reduce(x) # nhân tất cả giá trị trong mảng . 
print(a2)
a3=np.multiply.outer([1, 2, 3], [4, 5, 6]) # nhan hai mang 
print(a3)

6
0
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [147]:
#a1=np.add +
#a2=np.subtract -
#a3=np.multiply *
#A4=np.divide /
#a5=np.floor_divide chia lay phan nguyen
#a6=np.power luy thua 
#a7=np.mod chia lay phan du 
#a8=np.negative phep lay nguoc dau 
# Create sample arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition (a1 = np.add)
print("Addition:")
print(np.add(arr1, arr2))  # Or simply arr1 + arr2

# Subtraction (a2 = np.subtract)
print("\nSubtraction:")
print(np.subtract(arr1, arr2))  # Or simply arr1 - arr2

# Multiplication (a3 = np.multiply)
print("\nMultiplication:")
print(np.multiply(arr1, arr2))  # Or simply arr1 * arr2

# Division (A4 = np.divide)
print("\nDivision:")
print(np.divide(arr1, arr2))  # Or simply arr1 / arr2 (notice it performs floating-point division)

# Floor division (a5 = np.floor_divide)
print("\nFloor Division (integer quotient):")
print(np.floor_divide(arr1, arr2))

# Power (a6 = np.power)
print("\nPower:")
print(np.power(arr1, 2))  # Or simply arr1 ** 2

# Modulo (a7 = np.mod)
print("\nModulo (remainder):")
print(np.mod(arr1, 2))  # Or simply arr1 % 2

# Negative (a8 = np.negative)
print("\nNegative:")
print(np.negative(arr1))  # Or simply -arr1

Addition:
[5 7 9]

Subtraction:
[-3 -3 -3]

Multiplication:
[ 4 10 18]

Division:
[0.25 0.4  0.5 ]

Floor Division (integer quotient):
[0 0 0]

Power:
[1 4 9]

Modulo (remainder):
[1 0 1]

Negative:
[-1 -2 -3]


Mỗi mảng sẽ có 3 thuộc tính chính:

- **ndim**: số chiều của mảng
- **shape**: kích thước của từng chiều
- **size**: tổng kích thước của mảng (bằng số lượng phần tử trong mảng)

In [148]:
a1 = np.random.randint(10, size=5) # Mảng 1 chiều
a2 = np.random.randint(10, size=(3, 4)) # Mảng 2 chiều
a3 = np.random.randint(10, size=(3, 4, 5)) # Mảng 3 chiều

print("a2 ndim: ", a2.ndim)
print("a2 shape: ", a2.shape)
print("a2 size: ", a2.size)

a2 ndim:  2
a2 shape:  (3, 4)
a2 size:  12


In [149]:
#a[start:stop:step] 

x2 = np.random.randint(10, size=(3, 4))
print("x2 = \n", x2)
 
print("Lấy 2 hàng và 3 cột: \n", x2[:2, :3])
print("Lấy tất cả các hàng, còn lấy các cột với bước nhảy là 2:\n ", x2[:, ::2])
print("Lấy cột đầu tiên: ", x2[:, 0])
print("Lấy hàng đầu tiên", x2[0, :])
print("Tương tự như x2[0, :]", x2[0]) 

x2 = 
 [[3 6 9 9]
 [6 4 1 8]
 [3 3 8 7]]
Lấy 2 hàng và 3 cột: 
 [[3 6 9]
 [6 4 1]]
Lấy tất cả các hàng, còn lấy các cột với bước nhảy là 2:
  [[3 9]
 [6 1]
 [3 8]]
Lấy cột đầu tiên:  [3 6 3]
Lấy hàng đầu tiên [3 6 9 9]
Tương tự như x2[0, :] [3 6 9 9]


In [151]:
# nối mảng 
x = np.array([0, 1, 2, 3])
y = np.array([3, 2, 1, 0])
 
print("Phương thức concatenate nhận tham số đầu tiên là một tuple hoặc mảng: ", np.concatenate([x, y]))
print("Phương thức concatenate có thể nối nhiều hơn 2 mảng một lúc: ", np.concatenate([x, y, x, y]))
 
x_grid = np.array([[1,2,3], 
                   [4,5,6]])
print("Sử dụng cho mảng nhiều chiều, nối 2 mảng theo trục đầu tiên (chiều dọc):\n ", np.concatenate([x_grid, x_grid]))
print("Hoặc nối 2 mảng theo trục thứ 2 (chiều ngang): \n", np.concatenate([x_grid, x_grid], axis=1))
x = np.array([1,2,3])
x_grid = np.array([[4,5,6], 
                   [7,8,9]])
 
print("Nối 2 mảng theo chiều dọc:\n ", np.vstack([x, x_grid]))
 
y = np.array([[99],
             [99]])
print("Nối 2 mảng theo chiều ngang: \n", np.hstack([x_grid, y]))


Phương thức concatenate nhận tham số đầu tiên là một tuple hoặc mảng:  [0 1 2 3 3 2 1 0]
Phương thức concatenate có thể nối nhiều hơn 2 mảng một lúc:  [0 1 2 3 3 2 1 0 0 1 2 3 3 2 1 0]
Sử dụng cho mảng nhiều chiều, nối 2 mảng theo trục đầu tiên (chiều dọc):
  [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
Hoặc nối 2 mảng theo trục thứ 2 (chiều ngang): 
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
Nối 2 mảng theo chiều dọc:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Nối 2 mảng theo chiều ngang: 
 [[ 4  5  6 99]
 [ 7  8  9 99]]


In [155]:
# chia mảng 
x = [1,2,3,4,5,6,3,2,1]
x1, x2, x3 = np.split(x, [3, 5])
print("x1, x2, x3 = ", x1, x2, x3)
 
grid = np.arange(16).reshape((4, 4))
print("grid = \n", grid)
tren, duoi = np.vsplit(grid, [2])
print("Trên:\n", tren)
print("Dưới:\n", duoi)
trai, phai = np.hsplit(grid, [2])
print("Trái:\n", trai)
print("Phải:\n", phai)
 
x = np.arange(16).reshape(2, 2, 4)
print("x = \n", x)
print("Chia với theo axis = 2: \n")
print(np.dsplit(x, 2))

x1, x2, x3 =  [1 2 3] [4 5] [6 3 2 1]
grid = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Trên:
 [[0 1 2 3]
 [4 5 6 7]]
Dưới:
 [[ 8  9 10 11]
 [12 13 14 15]]
Trái:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Phải:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
x = 
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
Chia với theo axis = 2: 

[array([[[ 0,  1],
        [ 4,  5]],

       [[ 8,  9],
        [12, 13]]]), array([[[ 2,  3],
        [ 6,  7]],

       [[10, 11],
        [14, 15]]])]


In [157]:
arr = np.array([[9, 13], 
              [5, 2]]) 
 
print ("Sort theo cột : \n", np.sort(arr, axis = 0))         
    
print ("\nSort theo hàng : \n", np.sort(arr, axis = 1)) 
    
print ("\nSort không theo trục : \n", np.sort(arr, axis=None))

Sort theo cột : 
 [[ 5  2]
 [ 9 13]]

Sort theo hàng : 
 [[ 9 13]
 [ 2  5]]

Sort không theo trục : 
 [ 2  5  9 13]


In [159]:
arr = np.array([8, 2, 1, 7, 4, 3, 9]) 
    
print("arr = ", arr)
 
print("Mảng đã sắp xếp: ", np.sort(arr))
print("Vị trí tương ứng của các phần tử đã sắp xếp so với ban đầu: ", np.argsort(arr))

arr =  [8 2 1 7 4 3 9]
Mảng đã sắp xếp:  [1 2 3 4 7 8 9]
Vị trí tương ứng của các phần tử đã sắp xếp so với ban đầu:  [2 1 5 4 3 0 6]


In [161]:
#gia tri trung binh 
# mảng 1 chiều 
X = [1, 2, 3, 4, 5]
print("Mean X = ", np.mean(X)) 
# mảng nhiều chiều 
X = np.array([[1, 2], [3, 4]])
print("Mean X = ", np.mean(X))
print("Mean X với axis = 0: ", np.mean(X, axis=0))
print("Mean X với axis = 1: ", np.mean(X, axis=1))

# Lưu ý : với định dạng single precision (float32), mean có thể không chính xác với các mảng lớn:
a = np.zeros((2, 512*512), dtype=np.float32)
a[0, :] = 1.0
a[1, :] = 0.1
print("a.shape: ", a.shape)
print("mean a = ", np.mean(a))
print("mean a = ", np.mean(a, dtype=np.float64))

Mean X =  3.0
Mean X =  2.5
Mean X với axis = 0:  [2. 3.]
Mean X với axis = 1:  [1.5 3.5]
a.shape:  (2, 262144)
mean a =  0.54999924
mean a =  0.5500000007450581


In [163]:
# trung vi 
X = np.array([2, 5, 3, 1, 7])
Y = np.array([2, 1, 8, 5, 7, 9])
# tính giá trị trung vị mảng 1 chiều : 
print("Median X = ", np.median(X))
print("Median Y = ", np.median(Y))
# giá trị trung vị mảng nhiều chiều : 
arr = np.array([[7, 4, 2], [3, 9, 5]])
print("median arr (axis = 0) = ", np.median(arr, axis=0))
print("median arr (axis = 1) = ", np.median(arr, axis=1))

Median X =  3.0
Median Y =  6.0
median arr (axis = 0) =  [5.  6.5 3.5]
median arr (axis = 1) =  [4. 5.]


In [165]:
#xu li nan va medium 
x = np.array([2, np.nan, 5, 9])
print("mean = ", np.nanmean(x))
print("median = ", np.nanmedian(x))

mean =  5.333333333333333
median =  5.0


In [167]:
freetuts_ages = [19, 33, 51, 22, 18, 13, 45, 24, 58, 11, 25, 27, 26, 29]
 
print("Phương sai: ", np.var(freetuts_ages))
print("Độ lệch chuẩn: ", np.std(freetuts_ages))

# xử lý nan trong ps & dlc 
a = np.array([1, np.nan, 3, 4])
print("var = ", np.var(a))
print("std = ", np.std(a))
print("nanvar = ", np.nanvar(a))
print("nanstd = ", np.nanstd(a))

Phương sai:  178.51530612244895
Độ lệch chuẩn:  13.360962020844493
var =  nan
std =  nan
nanvar =  1.5555555555555554
nanstd =  1.247219128924647


In [171]:
x = np.array([[14, 96],
               [46, 82],
               [80, 67],
               [77, 91],
               [99, 87]])
 
print("X = ", x)
 
print("Giá trị lớn nhất: ", np.amax(x))
print("Giá trị bé nhất: ", np.amin(x))
 
print("Giá trị lớn nhất (axis = 0): ", np.amax(x, axis=0))
print("Giá trị lớn nhất (axis = 1): ", np.amax(x, axis=1))
# bo qua phan tu nan 
x = np.array([[14, 96],
               [np.nan, 82],
               [80, 67],
               [77, np.nan],
               [99, 87]])
 
print("X = \n", x)
 
print("Giá trị lớn nhất: ", np.nanmax(x))
print("Giá trị bé nhất: ", np.nanmin(x))

X =  [[14 96]
 [46 82]
 [80 67]
 [77 91]
 [99 87]]
Giá trị lớn nhất:  99
Giá trị bé nhất:  14
Giá trị lớn nhất (axis = 0):  [99 96]
Giá trị lớn nhất (axis = 1):  [96 82 80 91 99]
X = 
 [[14. 96.]
 [nan 82.]
 [80. 67.]
 [77. nan]
 [99. 87.]]
Giá trị lớn nhất:  99.0
Giá trị bé nhất:  14.0


In [172]:
x = np.array([[1, 5, 7],
              [2, 3, 4]])

print("Range = ", np.ptp(x))
print("Range (axis = 0) = ", np.ptp(x, axis=0))
print("Range (axis = 1) = ", np.ptp(x, axis=1))

Range =  6
Range (axis = 0) =  [1 2 3]
Range (axis = 1) =  [6 2]


**Range = 6có nghĩa là sự khác biệt giữa giá trị lớn nhất (7) và nhỏ nhất (1) trong toàn bộ mảng là** 6.
**Range (axis = 0)hiển thị phạm vi cho mỗi cột:** 
[4 (5-1), 2 (3-1), 3 (7-4)].
**Range (axis = 1)hiển thị phạm vi cho mỗi hàng:** 
[4 (7-3), 2 (4-2), 1 (5-4)].

In [174]:
scores = np.array([8, 6, 4, 3, 9, 4, 7, 4, 4, 9, 7, 3, 9, 4, 2, 3, 8, 5, 9, 6])
 
print("Bách phân vị thứ 70: ", np.percentile(scores, 70, interpolation='lower'))
print("Bách phân vị thứ 70: ", np.percentile(scores, 70, interpolation='higher'))
print("Bách phân vị thứ 70: ", np.percentile(scores, 70, interpolation='linear'))
print("Bách phân vị thứ 70: ", np.percentile(scores, 70, interpolation='nearest'))
print("Bách phân vị thứ 70: ", np.percentile(scores, 70, interpolation='midpoint'))

Bách phân vị thứ 70:  7
Bách phân vị thứ 70:  8
Bách phân vị thứ 70:  7.299999999999999
Bách phân vị thứ 70:  7
Bách phân vị thứ 70:  7.5


In [176]:
#  tu vi phan
print("Q1 = : ", np.quantile(scores, 0.25))
print("Q2 = : ", np.quantile(scores, 0.5))
print("Q3 = : ", np.quantile(scores, 0.75))

Q1 = :  4.0
Q2 = :  5.5
Q3 = :  8.0


In [178]:
# bai toan xs 
np.random.randint(0, 2) # Ngẫu nhiên số nguyên trong khoảng [0, 2) 

# tung 1000 đồng xu : 
coins = np.random.randint(2, size=1000) 
print(coins.shape) 

print("% số lần tung được mặt ngửa: ", (coins == 0).mean() * 100)
print("% số lần tung được mặt úp: ", (coins == 1).mean() * 100)

(1000,)
% số lần tung được mặt ngửa:  50.7
% số lần tung được mặt úp:  49.3


In [180]:
coins = np.random.choice([0, 1], size=1000, p=[0.2, 0.8])
# random.choice sẽ lấy ngẫu nhiên các phần tử trong mảng ở tham số đầu tiên với xác suất ở tham số p
print("% số lần tung được mặt ngửa: ", (coins == 0).mean() * 100)
print("% số lần tung được mặt úp: ", (coins == 1).mean() * 100)

% số lần tung được mặt ngửa:  19.8
% số lần tung được mặt úp:  80.2


In [183]:
np.random.binomial(20, 0.5) # Số mặt ngửa nhận được khi tung đồng xu 10 lần -> 9 
np.random.binomial(20, 0.5, 10) # Số mặt ngửa nhận được khi tung đồng xu 20 lần trong 10 lần lặp
print("Trung bình số mặt ngửa nhận được khi tung đồng xu 20 lần trong vòng 10 lần lặp: ", np.random.binomial(20, 0.5, 10).mean())

# ứng dụng : 
n = 10 # tung 10 đồng xu trong 1 lần
p = 0.2 # bias cho mặt ngửa (xác suất cho mặt ngửa là 0.2)
l = 1000 # số lần lặp
 
b = np.random.binomial(n, p, l)
print("Trung bình số mặt ngửa nhận được: "), b.mean()

Trung bình số mặt ngửa nhận được khi tung đồng xu 20 lần trong vòng 10 lần lặp:  9.5
Trung bình số mặt ngửa nhận được: 


(None, 1.995)

In [185]:
#random seed
# 1
g = np.random
g.seed(10)
 
print("g rand: ", g.rand()) 
# 2
e = np.random
e.seed(10)
 
print("e rand: ", e.rand())

g rand:  0.771320643266746
e rand:  0.771320643266746


In [187]:
a = np.random.rand()
b = np.random.rand(4) # Mảng có 1x8 phần tử
c = np.random.rand(2, 3) # Mảng có 2x3 phần tử
 
print("a = ", a)
print("b = ", b)
print("c = ", c)

a =  0.003948266327914451
b =  [0.51219226 0.81262096 0.61252607 0.72175532]
c =  [[0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076]]


In [191]:
np.random.normal(loc=0.0, scale=1.0, size=None) # loc = mean, scale = standard deviation

m, sigma = 0, 0.1 # mean và standard deviation
s = np.random.normal(m, sigma, size=5)
s

array([ 0.04176597,  0.08939577,  0.00473552, -0.06084255, -0.02685481])

In [193]:
# Hàm này sẽ sinh ra một mảng có giá trị phân phối đều (uniform distribution) trong một khoảng nhất định cho trước. 
np.random.uniform(low=0.0, high=1.0, size=None)

# numpy.random.permutation : Mục đích của hàm chính là tạo nên một dãy hoán vị 
np.random.permutation(x) 
p = np.random.permutation(10)
print(p)

[1 6 3 5 9 2 8 0 7 4]


In [195]:
# doc them 

# Đây là một hàm giúp thêm 1 trường mới vào mảng sẵn có 
#numpy.lib.recfunctions.append_fields(base, names, data, dtypes=None, fill_value=-1, usemask=True, asrecarray=False) 
#base: Mảng cần mở rộng
#names: Tên trường
#data: Dữ liệu của trường
#dtypes: Kiểu dữ liệu của trường, nếu không điền thì sẽ tự động định dạng
#fill_value: Giá trị được dùng để điền dữ liệu nếu dữ liệu trong trường bị thiếu
#usemask: Có trả về MaskedArray hay không
#asrecarray: Có trả về RecordArrays hay không
#print("Family: ", family) 
#rfn.append_fields(family, 'weight', [75, 50]) #Chỉ thêm dữ liệu cho 2 người đầu 

# rfn.drop_fields Hàm này loại bỏ các trường được chỉ định và trả về một mảng mới
#numpy.lib.recfunctions.drop_fields(base, drop_names, usemask=True, asrecarray=False)
#base: Mảng cần loại bỏ
#drop_names: Tên trường cần bỏ
#rfn.drop_fields(base=family, drop_names='age') 

#rfn.rename_fields  Hàm này thay đổi tên các trường được chỉ định.
#numpy.lib.recfunctions.rename_fields(base, namemapper)
#base: Mảng cần đổi
#namemapper: Có kiểu dữ liệu dictionary chứa tên cũ và tên mới của trường tương đương
#rfn.rename_fields(base=family, namemapper={'age': 'Tuổi', 'name': 'Tên', 'height': 'Chiều cao'})

Chú ý bai trc 

In [198]:
#lambda arguments : expression
x = lambda a : a + 10
print(x(5))

15


In [200]:
def myfunc(n):
  return lambda a : a * n

mytripler = myfunc(3)

print(mytripler(11))

33
